# Copyright 2008 Bernd Steinhauser <berniyh@exherbo.org>
# Distributed under the terms of the GNU General Public License v2

# Add a local FPATH
if [[ -d /etc/zsh/site-functions ]]; then
	FPATH=/etc/zsh/site-functions:${FPATH}
fi

HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000

setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt APPEND_HISTORY
setopt CORRECT
setopt EXTENDED_HISTORY
#setopt MENUCOMPLETE
setopt ALL_EXPORT

setopt appendhistory autocd beep extendedglob nomatch
setopt correctall

zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
#zmodload -ap zsh/mapfile mapfile

alias ls='ls --color=auto'

selfupdate() {
    ZSHRC_URL="http://github.com/michaelforney/playground/raw/master/zsh/zshrc"
    echo "Updating zshrc from $ZSHRC_URL..."
    echo "Press Ctrl+C within 5 seconds to abort..."
    sleep 5
    case `uname -s` in
    Linux)
        ZSHRC_FILE=/etc/zsh/zshrc;;
    *)
        ZSHRC_FILE=/etc/zshrc;;
    esac
    cp $ZSHRC_FILE /tmp/zshrc.bak
    sudo wget $ZSHRC_URL -O $ZSHRC_FILE
    echo "Done. Old zshrc saved to /tmp/zshrc"
}

uppatch() {
    local srcfile destfile
    if [[ -f "${1}" ]] ; then
        srcfile=${1}
        destfile=$(basename ${srcfile} | sed -e "s/ /_/")
    elif [[ ! -t 0 ]] ; then
        srcfile=$(tempfile -m 0664)
        cat > ${srcfile}
        destfile=$(date +%s).patch
    else
        echo "Usage: uppatch patchfile OR uppatch < patchfile"
        return 1
    fi
    scp "${srcfile}" mforney@obberon.com:~/public_html/exherbo-patches/${destfile}
    if [[ ! -t 0 ]] ; then
        rm ${srcfile}
    fi
    local url="http://obberon.com/exherbo-patches/${destfile}"
    echo -n ${url} | xclip
    echo ${url}
    return 0
}

setprompt () {
    ###
    # Need this so the prompt will work.

    setopt prompt_subst


    ###
    # See if we can use colors.

    autoload colors zsh/terminfo
    if [[ "$terminfo[colors]" -ge 8 ]]; then
        colors
    fi
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
        eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
        eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
        (( count = $count + 1 ))
    done
    PR_NO_COLOR="%{$terminfo[sgr0]%}"

    ###
    # Finally, the prompt.
    case $HOST in
    michael)
        HOST_COLOR=$PR_GREEN;;
    michael-laptop)
        HOST_COLOR=$PR_BLUE;;
    fileserver)
        HOST_COLOR=$PR_LIGHT_RED;;
    esac

    if [[ $UID = 0 ]] ; then
        USER_COLOR=$PR_RED
    else
        case $USER in
        michael)
            USER_COLOR=$PR_LIGHT_GREEN;;
        mediapc)
            USER_COLOR=$PR_LIGHT_BLUE;;
        *)
            USER_COLOR=$PR_LIGHT_WHITE;;
        esac
    fi
    PROMPT=$PR_WHITE"[$USER_COLOR%n$PR_WHITE@$HOST_COLOR%m$PR_WHITE:$PR_LIGHT_YELLOW%3c$PR_WHITE] %(!.#.$) $PR_NO_COLOR"
    RPROMPT="$PR_LIGHT_CYAN(%D{%a %H:%M})$PR_NO_COLOR"
}

autoload -Uz compinit
compinit

setprompt

