# Copyright 2008 Bernd Steinhauser <berniyh@exherbo.org>
# Distributed under the terms of the GNU General Public License v2

# Add a local FPATH
if [[ -d /etc/zsh/site-functions ]]; then
	FPATH=/etc/zsh/site-functions:${FPATH}
fi

HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000

setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt APPEND_HISTORY
setopt CORRECT
setopt EXTENDED_HISTORY
#setopt MENUCOMPLETE
setopt ALL_EXPORT

setopt appendhistory autocd beep extendedglob nomatch
setopt correctall

zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

alias ls='ls --color=auto'

selfupdate() {
    ZSHRC_URL="http://github.com/michaelforney/playground/raw/master/zsh/zshrc"
    echo "Updating zshrc from $URL..."
    echo "Press Ctrl+C within 5 seconds to abort..."
    sleep 5
    cp /etc/zsh/zshrc /tmp/zshrc.bak
    sudo wget $ZSHRC_URL -O /etc/zsh/zshrc
    echo "Done. Old zshrc saved to /tmp/zshrc"
}

setprompt () {
    ###
    # Need this so the prompt will work.

    setopt prompt_subst


    ###
    # See if we can use colors.

    autoload colors zsh/terminfo
    if [[ "$terminfo[colors]" -ge 8 ]]; then
        colors
    fi
    for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
        eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
        eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
        (( count = $count + 1 ))
    done
    PR_NO_COLOR="%{$terminfo[sgr0]%}"

    ###
    # Finally, the prompt.

    HOST_COLOR=$PR_GREEN
    case $USER in
    michael)
        USER_COLOR=$PR_LIGHT_GREEN;;
    mediapc)
        USER_COLOR=$PR_LIGHT_BLUE;;
    root)
        USER_COLOR=$PR_RED;;
    *)
        USER_COLOR=$PR_LIGHT_WHITE;;
    esac
    PROMPT="[$USER_COLOR%n$PR_BLUE@$HOST_COLOR%m:$PR_LIGHT_YELLOW%2c$PR_NO_COLOR] %(!.#.$) "
    RPROMPT="$PR_LIGHT_CYAN(%D{%a %H:%M})$PR_NO_COLOR"
}

autoload -Uz compinit
compinit

setprompt

